// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJy1elVwM6LM9wIBDdaUJOxkhZVhoYZ8Y',
    appId: '1:35560980218:web:94b65eef2afa846c00d343',
    messagingSenderId: '35560980218',
    projectId: 'hestia-7055f',
    authDomain: 'hestia-7055f.firebaseapp.com',
    storageBucket: 'hestia-7055f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDienDFTSeUaJDJmW5pMCJ-yOXVTt1k0CY',
    appId: '1:35560980218:android:d5d51107bcd01db400d343',
    messagingSenderId: '35560980218',
    projectId: 'hestia-7055f',
    storageBucket: 'hestia-7055f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabZn8sJttrtwT_vkH9_tk8QL5yOK4I_M',
    appId: '1:35560980218:ios:850ca244260a12e600d343',
    messagingSenderId: '35560980218',
    projectId: 'hestia-7055f',
    storageBucket: 'hestia-7055f.appspot.com',
    iosClientId: '35560980218-js8stmrqcffi4rotalk1qv3lpk6k8rap.apps.googleusercontent.com',
    iosBundleId: 'com.example.histia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabZn8sJttrtwT_vkH9_tk8QL5yOK4I_M',
    appId: '1:35560980218:ios:850ca244260a12e600d343',
    messagingSenderId: '35560980218',
    projectId: 'hestia-7055f',
    storageBucket: 'hestia-7055f.appspot.com',
    iosClientId: '35560980218-js8stmrqcffi4rotalk1qv3lpk6k8rap.apps.googleusercontent.com',
    iosBundleId: 'com.example.histia',
  );
}
